mod 'puppetlabs/stdlib'
mod 'puppetlabs/firewall'
mod 'shearn89/toughen'
mod 'puppetlabs/limits'
mod 'thias/sysctl'
mod 'puppetlabs/ntp'
mod 'herculesteam/augeasproviders_core'
mod 'herculesteam/augeasproviders_grub'
mod 'kemra102/auditd'
mod 'puppetlabs/concat'
mod 'puppet/selinux'

